networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foodgram_user -d foodgram"]
      interval: 5s
      retries: 5
      timeout: 3s

  backend:
    image: klinicwork/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./backend/data:/app/data
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    env_file: .env
    image: klinicwork/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    networks:
      - app-network

  gateway:
    image: klinicwork/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 7777:80
    volumes:
      - static:/static
      - media:/media
    networks:
      - app-network

volumes:
  pg_data:
  static:
  media: